name: CI/CD for Personal Portfolio

on:
  push:
    branches:
      - workflow  # Replace with your branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Deploy
      run: |
        # Add your build commands here (if any)
        # For a simple HTML/CSS project, you might not need this

        aws s3 sync ./ s3://vssproject.com
      env:
        AWS_ACCESS_KEY_ID: M3Pc4ePuNmjAC7BvGnf7OSEBcuDFydNihxt0P7lY
        AWS_SECRET_ACCESS_KEY: M3Pc4ePuNmjAC7BvGnf7OSEBcuDFydNihxt0P7lY

